/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:eaf9e55e-0bbe-4605-95c6-97c1b728984a",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_DkcOV67sf",
    "aws_user_pools_web_client_id": "2qhaje25kk4qt92sg30tlo4f4n",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://kes3mh6n7rhhpmssnxf4bi2n2y.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456"
};


export default awsmobile;
